name: Pack & Publish NuGet
description: Call workflow in pipelines to package and publish NuGet package to Github
author: Nichals Hoberg

on:
    push:
        branches: main
    pull_request:
      branches: main

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true
    
jobs:
    build:
        uses: FamilySync/pipelines/.github/workflows/dotnet/nuget-publish.yaml@main
        secrets: inherit